
export const INITIAL_SESSIONS: Session[] = [];

// Empty chart data structure
export const PROGRESS_DATA = [
  { name: 'Sat', pages: 0 },
  { name: 'Sun', pages: 0 },
  { name: 'Mon', pages: 0 },
  { name: 'Tue', pages: 0 },
  { name: 'Wed', pages: 0 },
  { name: 'Thu', pages: 0 },
  { name: 'Fri', pages: 0 },
];

// Total pages in the Quran
export const TOTAL_QURAN_PAGES = 604;

export const SURAH_NAMES = [
  { id: 1, nameAr: "الفاتحة", nameEn: "Al-Fatiha", startPage: 1 },
  { id: 2, nameAr: "البقرة", nameEn: "Al-Baqarah", startPage: 2 },
  { id: 3, nameAr: "آل عمران", nameEn: "Al-Imran", startPage: 50 },
  { id: 4, nameAr: "النساء", nameEn: "An-Nisa", startPage: 77 },
  { id: 5, nameAr: "المائدة", nameEn: "Al-Ma'idah", startPage: 106 },
  { id: 6, nameAr: "الأنعام", nameEn: "Al-An'am", startPage: 128 },
  { id: 7, nameAr: "الأعراف", nameEn: "Al-A'raf", startPage: 151 },
  { id: 8, nameAr: "الأنفال", nameEn: "Al-Anfal", startPage: 177 },
  { id: 9, nameAr: "التوبة", nameEn: "At-Tawbah", startPage: 187 },
  { id: 10, nameAr: "يونس", nameEn: "Yunus", startPage: 208 },
  { id: 11, nameAr: "هود", nameEn: "Hud", startPage: 221 },
  { id: 12, nameAr: "يوسف", nameEn: "Yusuf", startPage: 235 },
  { id: 13, nameAr: "الرعد", nameEn: "Ar-Ra'd", startPage: 249 },
  { id: 14, nameAr: "إبراهيم", nameEn: "Ibrahim", startPage: 255 },
  { id: 15, nameAr: "الحجر", nameEn: "Al-Hijr", startPage: 262 },
  { id: 16, nameAr: "النحل", nameEn: "An-Nahl", startPage: 267 },
  { id: 17, nameAr: "الإسراء", nameEn: "Al-Isra", startPage: 282 },
  { id: 18, nameAr: "الكهف", nameEn: "Al-Kahf", startPage: 293 },
  { id: 19, nameAr: "مريم", nameEn: "Maryam", startPage: 305 },
  { id: 20, nameAr: "طه", nameEn: "Ta-Ha", startPage: 312 },
  { id: 21, nameAr: "الأنبياء", nameEn: "Al-Anbiya", startPage: 322 },
  { id: 22, nameAr: "الحج", nameEn: "Al-Hajj", startPage: 332 },
  { id: 23, nameAr: "المؤمنون", nameEn: "Al-Mu'minun", startPage: 342 },
  { id: 24, nameAr: "النور", nameEn: "An-Nur", startPage: 350 },
  { id: 25, nameAr: "الفرقان", nameEn: "Al-Furqan", startPage: 359 },
  { id: 26, nameAr: "الشعراء", nameEn: "Ash-Shu'ara", startPage: 367 },
  { id: 27, nameAr: "النمل", nameEn: "An-Naml", startPage: 377 },
  { id: 28, nameAr: "القصص", nameEn: "Al-Qasas", startPage: 385 },
  { id: 29, nameAr: "العنكبوت", nameEn: "Al-Ankabut", startPage: 396 },
  { id: 30, nameAr: "الروم", nameEn: "Ar-Rum", startPage: 404 },
  { id: 31, nameAr: "لقمان", nameEn: "Luqman", startPage: 411 },
  { id: 32, nameAr: "السجدة", nameEn: "As-Sajdah", startPage: 415 },
  { id: 33, nameAr: "الأحزاب", nameEn: "Al-Ahzab", startPage: 418 },
  { id: 34, nameAr: "سبأ", nameEn: "Saba", startPage: 428 },
  { id: 35, nameAr: "فاطر", nameEn: "Fatir", startPage: 434 },
  { id: 36, nameAr: "يس", nameEn: "Ya-Sin", startPage: 440 },
  { id: 37, nameAr: "الصافات", nameEn: "As-Saffat", startPage: 446 },
  { id: 38, nameAr: "ص", nameEn: "Sad", startPage: 453 },
  { id: 39, nameAr: "الزمر", nameEn: "Az-Zumar", startPage: 458 },
  { id: 40, nameAr: "غافر", nameEn: "Ghafir", startPage: 467 },
  { id: 41, nameAr: "فصلت", nameEn: "Fussilat", startPage: 477 },
  { id: 42, nameAr: "الشورى", nameEn: "Ash-Shura", startPage: 483 },
  { id: 43, nameAr: "الزخرف", nameEn: "Az-Zukhruf", startPage: 489 },
  { id: 44, nameAr: "الدخان", nameEn: "Ad-Dukhan", startPage: 496 },
  { id: 45, nameAr: "الجاثية", nameEn: "Al-Jathiyah", startPage: 499 },
  { id: 46, nameAr: "الأحقاف", nameEn: "Al-Ahqaf", startPage: 502 },
  { id: 47, nameAr: "محمد", nameEn: "Muhammad", startPage: 507 },
  { id: 48, nameAr: "الفتح", nameEn: "Al-Fath", startPage: 511 },
  { id: 49, nameAr: "الحجرات", nameEn: "Al-Hujurat", startPage: 515 },
  { id: 50, nameAr: "ق", nameEn: "Qaf", startPage: 518 },
  { id: 51, nameAr: "الذاريات", nameEn: "Ad-Dhariyat", startPage: 520 },
  { id: 52, nameAr: "الطور", nameEn: "At-Tur", startPage: 523 },
  { id: 53, nameAr: "النجم", nameEn: "An-Najm", startPage: 526 },
  { id: 54, nameAr: "القمر", nameEn: "Al-Qamar", startPage: 528 },
  { id: 55, nameAr: "الرحمن", nameEn: "Ar-Rahman", startPage: 531 },
  { id: 56, nameAr: "الواقعة", nameEn: "Al-Waqi'ah", startPage: 534 },
  { id: 57, nameAr: "الحديد", nameEn: "Al-Hadid", startPage: 537 },
  { id: 58, nameAr: "المجادلة", nameEn: "Al-Mujadila", startPage: 542 },
  { id: 59, nameAr: "الحشر", nameEn: "Al-Hashr", startPage: 545 },
  { id: 60, nameAr: "الممتحنة", nameEn: "Al-Mumtahanah", startPage: 549 },
  { id: 61, nameAr: "الصف", nameEn: "As-Saff", startPage: 551 },
  { id: 62, nameAr: "الجمعة", nameEn: "Al-Jumu'ah", startPage: 553 },
  { id: 63, nameAr: "المنافقون", nameEn: "Al-Munafiqun", startPage: 554 },
  { id: 64, nameAr: "التغابن", nameEn: "At-Taghabun", startPage: 556 },
  { id: 65, nameAr: "الطلاق", nameEn: "At-Talaq", startPage: 558 },
  { id: 66, nameAr: "التحريم", nameEn: "At-Tahrim", startPage: 560 },
  { id: 67, nameAr: "الملك", nameEn: "Al-Mulk", startPage: 562 },
  { id: 68, nameAr: "القلم", nameEn: "Al-Qalam", startPage: 564 },
  { id: 69, nameAr: "الحاقة", nameEn: "Al-Haqqah", startPage: 566 },
  { id: 70, nameAr: "المعارج", nameEn: "Al-Ma'arij", startPage: 568 },
  { id: 71, nameAr: "نوح", nameEn: "Nuh", startPage: 570 },
  { id: 72, nameAr: "الجن", nameEn: "Al-Jinn", startPage: 572 },
  { id: 73, nameAr: "المزمل", nameEn: "Al-Muzzammil", startPage: 574 },
  { id: 74, nameAr: "المدثر", nameEn: "Al-Muddaththir", startPage: 575 },
  { id: 75, nameAr: "القيامة", nameEn: "Al-Qiyamah", startPage: 577 },
  { id: 76, nameAr: "الإنسان", nameEn: "Al-Insan", startPage: 578 },
  { id: 77, nameAr: "المرسلات", nameEn: "Al-Mursalat", startPage: 580 },
  { id: 78, nameAr: "النبأ", nameEn: "An-Naba", startPage: 582 },
  { id: 79, nameAr: "النازعات", nameEn: "An-Nazi'at", startPage: 583 },
  { id: 80, nameAr: "عبس", nameEn: "Abasa", startPage: 585 },
  { id: 81, nameAr: "التكوير", nameEn: "At-Takwir", startPage: 586 },
  { id: 82, nameAr: "الإنفطار", nameEn: "Al-Infitar", startPage: 587 },
  { id: 83, nameAr: "المطففين", nameEn: "Al-Mutaffifin", startPage: 587 },
  { id: 84, nameAr: "الإنشقاق", nameEn: "Al-Inshiqaq", startPage: 589 },
  { id: 85, nameAr: "البروج", nameEn: "Al-Buruj", startPage: 590 },
  { id: 86, nameAr: "الطارق", nameEn: "At-Tariq", startPage: 591 },
  { id: 87, nameAr: "الأعلى", nameEn: "Al-A'la", startPage: 591 },
  { id: 88, nameAr: "الغاشية", nameEn: "Al-Ghashiyah", startPage: 592 },
  { id: 89, nameAr: "الفجر", nameEn: "Al-Fajr", startPage: 593 },
  { id: 90, nameAr: "البلد", nameEn: "Al-Balad", startPage: 594 },
  { id: 91, nameAr: "الشمس", nameEn: "Ash-Shams", startPage: 595 },
  { id: 92, nameAr: "الليل", nameEn: "Al-Lail", startPage: 595 },
  { id: 93, nameAr: "الضحى", nameEn: "Ad-Duha", startPage: 596 },
  { id: 94, nameAr: "الشرح", nameEn: "Ash-Sharh", startPage: 596 },
  { id: 95, nameAr: "التين", nameEn: "At-Tin", startPage: 597 },
  { id: 96, nameAr: "العلق", nameEn: "Al-Alaq", startPage: 597 },
  { id: 97, nameAr: "القدر", nameEn: "Al-Qadr", startPage: 598 },
  { id: 98, nameAr: "البينة", nameEn: "Al-Bayyinah", startPage: 598 },
  { id: 99, nameAr: "الزلزلة", nameEn: "Az-Zalzalah", startPage: 599 },
  { id: 100, nameAr: "العاديات", nameEn: "Al-Adiyat", startPage: 599 },
  { id: 101, nameAr: "القارعة", nameEn: "Al-Qari'ah", startPage: 600 },
  { id: 102, nameAr: "التكاثر", nameEn: "At-Takathur", startPage: 600 },
  { id: 103, nameAr: "العصر", nameEn: "Al-Asr", startPage: 601 },
  { id: 104, nameAr: "الهمزة", nameEn: "Al-Humazah", startPage: 601 },
  { id: 105, nameAr: "الفيل", nameEn: "Al-Fil", startPage: 601 },
  { id: 106, nameAr: "قريش", nameEn: "Quraish", startPage: 602 },
  { id: 107, nameAr: "الماعون", nameEn: "Al-Ma'un", startPage: 602 },
  { id: 108, nameAr: "الكوثر", nameEn: "Al-Kawthar", startPage: 602 },
  { id: 109, nameAr: "الكافرون", nameEn: "Al-Kafirun", startPage: 603 },
  { id: 110, nameAr: "النصر", nameEn: "An-Nasr", startPage: 603 },
  { id: 111, nameAr: "المسد", nameEn: "Al-Masad", startPage: 603 },
  { id: 112, nameAr: "الإخلاص", nameEn: "Al-Ikhlas", startPage: 604 },
  { id: 113, nameAr: "الفلق", nameEn: "Al-Falaq", startPage: 604 },
  { id: 114, nameAr: "الناس", nameEn: "An-Nas", startPage: 604 }
];

export const JUZ_NAMES = Array.from({ length: 30 }, (_, i) => ({
  id: i + 1,
  nameAr: `الجزء ${i + 1}`,
  nameEn: `Juz ${i + 1}`
}));
